# This file lists cops (rules) that we should follow before merging to master.
# Cops with a severity of error will fail the build.

# Any cops we haven't decided on (or haven't fixed yet) will be listed and
# ignored in the generated file `.rubocop_todo.yml`.
inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.arb'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Lint/UselessAssignment:
  Severity: error

Metrics/ClassLength:
  Severity: error
  Max: 200

Metrics/ModuleLength:
  Severity: error
  Max: 130

Metrics/MethodLength:
  Severity: error
  Max: 50

Metrics/LineLength:
  Severity: error
  AllowURI: true
  Max: 260 # Mostly arbitrary

Lint/BlockAlignment:
  Severity: warning

Lint/DefEndAlignment:
  Severity: warning

Style/Tab:
  Severity: warning

Style/StringMethods:
  Enabled: false
