Lint/AmbiguousOperator:
  Enabled: false
Lint/EndAlignment:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Rails/ActionFilter:
  Enabled: false
Rails/Date:
  Enabled: false
Rails/TimeZone:
  Enabled: false
Rails/Validation:
  Enabled: false
Style/AlignHash:
  Enabled: false
Style/AlignParameters:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/CaseIndentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/DeprecatedHashMethods:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Style/EmptyLinesAroundAccessModifier:
  Enabled: false
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/LeadingCommentSpace:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/MethodName:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/SpaceAfterComma:
  Enabled: false
Style/SpaceAfterControlKeyword:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/SpaceBeforeBlockBraces:
  Enabled: false
Style/SpaceInsideBlockBraces:
  Enabled: false
Style/SpaceInsideBrackets:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/SpaceInsideParens:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TrailingBlankLines:
  Enabled: false
Style/TrailingComma:
  Enabled: false
Style/VariableName:
  Enabled: false
